<?php
/**
 * ScorchedEarth.php
 * ============================================================
 * Embeds decoy records with specific sentinel UUIDs into the
 * database. These records are invisible to legitimate frontend
 * code — they are ONLY returned when an attacker uses SQL
 * injection, a compromised API key, or internal misconfiguration
 * to bypass normal query scoping.
 *
 * When a sentinel UUID appears in any request (GET, POST, DELETE),
 * the tripwire fires:
 *   1. Session immediately banned
 *   2. API key revoked
 *   3. WhatsApp + physical tracker alert
 *   4. Event logged as SCORCHED_EARTH_TRIGGER
 *
 * Decoy records are system-type aware:
 *   ECOMMERCE/PAYMENT  → fake merchant account, TZS 99,999,999 balance
 *   EDUCATION          → fake admin lecturer with perfect grades
 *   WIFI_MANAGEMENT    → fake unlimited-bandwidth master subscriber
 *   HEALTHCARE         → fake senior doctor with full access
 *   AGENCY             → fake platinum client, 10M followers
 * ============================================================
 */

namespace Aegis\Classes;

use Aegis\Config\Database;

class ScorchedEarth
{
    // UUID prefix that is NEVER generated by real business logic
    // If it appears in any request parameter, it is 100% attacker
    public const SENTINEL_PREFIX  = '0000DEAD-';
    public const SENTINEL_PATTERN = '/^0000DEAD-/';

    // Sentinel IDs per system type — embed these in decoy DB rows
    public const SENTINELS = [
        'ECOMMERCE'        => '0000DEAD-0000-0000-0000-MERCHANT9999',
        'SAAS'             => '0000DEAD-0000-0000-0000-WORKSPACE001',
        'HEALTHCARE'       => '0000DEAD-0000-0000-0000-PATIENT00001',
        'EDUCATION'        => '0000DEAD-0000-0000-0000-STUDENT00001',
        'WIFI_MANAGEMENT'  => '0000DEAD-0000-0000-0000-SUBSCRIBER01',
        'AGENCY'           => '0000DEAD-0000-0000-0000-CLIENTPLAT01',
        'PROPERTY'         => '0000DEAD-0000-0000-0000-LANDLORD0001',
        'GENERIC_BUSINESS' => '0000DEAD-0000-0000-0000-DECOYUSER001',
    ];

    // Decoy record templates — system-type aware fake bait data
    private const DECOY_RECORDS = [
        'ECOMMERCE' => [
            'type'    => 'merchant_account',
            'data'    => [
                'id'          => '0000DEAD-0000-0000-0000-MERCHANT9999',
                'name'        => 'System Test Account — DO NOT ACCESS',
                'balance_tzs' => 99999999,
                'balance_usd' => 999999,
                'status'      => 'active',
                'tier'        => 'PLATINUM',
                'api_key'     => 'sk_live_DECOY_DO_NOT_USE_00000000000000',
            ],
        ],
        'EDUCATION' => [
            'type' => 'staff_account',
            'data' => [
                'id'         => '0000DEAD-0000-0000-0000-STUDENT00001',
                'username'   => 'system.admin.cbe',
                'role'       => 'Super Admin',
                'student_id' => 'CBE0000000',
                'gpa'        => 4.0,
                'program'    => 'ADMIN',
                'all_grades' => 'EDITABLE',
            ],
        ],
        'WIFI_MANAGEMENT' => [
            'type' => 'master_subscriber',
            'data' => [
                'id'          => '0000DEAD-0000-0000-0000-SUBSCRIBER01',
                'username'    => 'master_bypass_account',
                'package'     => 'UNLIMITED_NO_CAP',
                'bandwidth'   => 'Unlimited',
                'balance'     => 9999999,
                'mac_address' => 'DE:AD:00:00:00:01',
                'status'      => 'privileged',
            ],
        ],
        'HEALTHCARE' => [
            'type' => 'admin_doctor',
            'data' => [
                'id'          => '0000DEAD-0000-0000-0000-PATIENT00001',
                'name'        => 'Dr. System Administrator',
                'role'        => 'Chief Medical Officer / System Admin',
                'access'      => 'ALL_WARDS_ALL_RECORDS',
                'patient_ids' => 'VIEWABLE',
            ],
        ],
        'AGENCY' => [
            'type' => 'platinum_client',
            'data' => [
                'id'       => '0000DEAD-0000-0000-0000-CLIENTPLAT01',
                'name'     => 'Internal Test Client — Privileged',
                'plan'     => 'PLATINUM_INTERNAL',
                'followers'=> 10000000,
                'revenue'  => 999999999,
                'api_key'  => 'ghk_INTERNAL_00000000000000000000',
            ],
        ],
        'SAAS' => [
            'type' => 'master_workspace',
            'data' => [
                'id'        => '0000DEAD-0000-0000-0000-WORKSPACE001',
                'name'      => 'Internal Admin Workspace',
                'plan'      => 'UNLIMITED',
                'api_key'   => 'sk_admin_INTERNAL_000000000000000',
                'all_data'  => 'ACCESSIBLE',
            ],
        ],
    ];

    private Database             $db;
    private AttackTracker        $tracker;
    private AlertNotifier        $notifier;

    public function __construct()
    {
        $this->db      = Database::getInstance();
        $this->tracker = new AttackTracker();
        $this->notifier= new AlertNotifier();
    }

    // ================================================================
    //  TRIPWIRE CHECK  —  call on every incoming request parameter
    // ================================================================

    /**
     * Check all request parameters for sentinel UUIDs.
     * Call this from Middleware on every request, before routing.
     *
     * @param array  $params   All GET/POST/route params merged
     * @param int    $siteId
     * @param string $sessionKey
     * @param string $systemType
     * @return bool  true if tripwire fired
     */
    public function checkRequest(
        array  $params,
        int    $siteId,
        string $sessionKey,
        string $systemType
    ): bool {
        $haystack = json_encode($params);

        // Check for any sentinel pattern in any parameter value
        if (!preg_match(self::SENTINEL_PATTERN, $haystack) &&
            !str_contains($haystack, self::SENTINEL_PREFIX)) {
            return false;
        }

        // Tripwire fired — full escalation
        $this->trigger($siteId, $sessionKey, $systemType, $haystack);
        return true;
    }

    /**
     * Check a single value (e.g. route param {id}) for sentinel UUID.
     */
    public function checkValue(string $value, int $siteId,
                               string $sessionKey, string $systemType): bool
    {
        if (!str_starts_with($value, self::SENTINEL_PREFIX)) return false;
        $this->trigger($siteId, $sessionKey, $systemType, $value);
        return true;
    }

    // ================================================================
    //  DECOY SEEDING  —  call once during site setup
    // ================================================================

    /**
     * Seeds decoy records for a site.
     * Call this when a site is first registered in Aegis.
     * Returns the sentinel UUID for this system type.
     */
    public function seedDecoys(int $siteId, string $systemType): string
    {
        $sentinel = self::SENTINELS[$systemType] ?? self::SENTINELS['GENERIC_BUSINESS'];
        $record   = self::DECOY_RECORDS[$systemType] ?? self::DECOY_RECORDS['ECOMMERCE'];

        // Store in aegis_decoy_users as a sentinel record
        $existing = $this->db->fetchOne(
            'SELECT id FROM aegis_decoy_users WHERE site_id = ? AND fake_email LIKE ?',
            [$siteId, '%0000DEAD%']
        );

        if (!$existing) {
            $this->db->query(
                'INSERT INTO aegis_decoy_users
                 (site_id, fake_username, fake_email, fake_role, fake_created_at)
                 VALUES (?, ?, ?, ?, ?)',
                [
                    $siteId,
                    $record['data']['username'] ?? 'system.decoy.account',
                    'decoy.' . $sentinel . '@aegis.internal',
                    $record['type'] ?? 'SENTINEL',
                    '2020-01-01 00:00:00',
                ]
            );
        }

        // Also seed in the general event table for visibility
        $this->db->query(
            'INSERT IGNORE INTO aegis_python_events
             (module, event_type, indicator, detail, severity, site_id)
             VALUES (?, ?, ?, ?, ?, ?)',
            [
                'deception_grid',
                'SCORCHED_EARTH_SEEDED',
                $sentinel,
                json_encode(['system_type' => $systemType, 'record' => $record]),
                'Low',
                $siteId,
            ]
        );

        return $sentinel;
    }

    /**
     * Returns the decoy record for the given system type.
     * This is what the attacker sees when they hit the tripwire.
     * (We serve them the bait data first, then ban them.)
     */
    public function getDecoyRecord(string $systemType): array
    {
        return self::DECOY_RECORDS[$systemType]['data']
            ?? self::DECOY_RECORDS['ECOMMERCE']['data'];
    }

    // ================================================================
    //  TRIPWIRE TRIGGER  —  fires when sentinel UUID is accessed
    // ================================================================

    private function trigger(int $siteId, string $sessionKey,
                             string $systemType, string $evidence): void
    {
        // 1. Log the critical event
        $client = $this->tracker->getClientDetails();
        $result = $this->tracker->logEvent(
            $siteId,
            'SCORCHED_EARTH_TRIGGER',
            null, null,
            $_SERVER['REQUEST_URI'] ?? '/',
            ['evidence' => substr($evidence, 0, 500), 'sentinel_accessed' => true]
        );

        // 2. Immediate ban — no threshold, no questions
        $this->tracker->ban(
            $siteId,
            $sessionKey,
            'Scorched Earth Tripwire: accessed sentinel UUID ' . self::SENTINEL_PREFIX
        );

        // 3. Escalate to WhatsApp + physical tracker
        $this->notifier->maybeAlert(
            99, // maximum severity — always fires
            $sessionKey,
            $client,
            'SCORCHED_EARTH_TRIGGER',
            true,
            null, null,
            $_SERVER['REQUEST_URI'] ?? '/'
        );

        // 4. Log to python_events for dashboard visibility
        $this->db->query(
            'INSERT INTO aegis_python_events
             (module, event_type, indicator, detail, severity, site_id)
             VALUES (?, ?, ?, ?, ?, ?)',
            [
                'deception_grid',
                'SCORCHED_EARTH_TRIGGERED',
                $client['ip'] ?? 'unknown',
                json_encode([
                    'session'     => $sessionKey,
                    'system_type' => $systemType,
                    'evidence'    => substr($evidence, 0, 200),
                ]),
                'Critical',
                $siteId,
            ]
        );
    }
}
